#!/bin/sh

setxkbmap -option compose:ralt
if lspci | grep -q "GeForce GTX 1070"; then
  ~/.screenlayout/home-dock.lt.sh
  bspc monitor DP-2 -d I II III IV V
  bspc monitor HDMI-0 -d VI VII VIII IX X
  pkill sxhkd; sxhkd -c ~/.config/sxhkd/sxhkdrc-dock &
else
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
  pkill sxhkd; sxhkd -c ~/.config/sxhkd/sxhkdrc-nodock &
fi

pkill dunst; dunst &

#autostart apps
picom --experimental-backends --backend glx -b --config ~/.config/picom/picom.conf &
feh --bg-fill ~/Documents/Personal/private-configs/wallpapers/mywall.png
~/.config/polybar/launch.sh &

# BSPWM
bspc config focus_follows_pointer true
bspc config top_padding 38
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle   true
bspc config window_gap 5
bspc config split_ratio 0.52
bspc config gapless_monocle      	true
bspc config single_monocle	 	false
bspc config focused_border_color 	\#FEFEFE
bspc config normal_border_color 	\#111824
bspc config initial_polarity 		first_child
bspc config automatic_scheme 		longest_side
bspc config pointer_modifier 		control
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_sidie

bspc config external_rules_command ~/.config/bspwm/external_rules.sh

if lspci | grep -q "GeForce GTX 1070"; then
  bspc desktop "^6" -l monocle
  bspc rule -a Firefox:Navigator desktop='^6' follow=off state=tiled focus=off
  bspc rule -a Firefox:Places desktop='^6' follow=off state=floating focus=off
  bspc rule -a Firefox:Firefox desktop='^6' follow=off state=floating focus=off
  bspc rule -a Thunderbird desktop='^8' follow=off state=tiled focus=off
  bspc rule -a Thunderbird:Calendar state=floating focus=on
  bspc rule -a Slack desktop='^10' state=tiled focus=off
  bspc rule -a TelegramDesktop desktop='^2' follow=off state=floating focus=off
  bspc rule -a yakuake sticky=on state=floating layer=above
  bspc rule -a Yad sticky=on state=floating layer=above
  bspc rule -a obsidian desktop='^9' follow=on focus=on state=tiled
  bspc rule -a dolphin desktop='^3' follow=on focus=on state=tiled
  bspc rule -a FortiClient desktop='^9' follow=off focus=on state=floating
else
  bspc desktop "^1" -l monocle
  bspc rule -a Firefox:Navigator desktop='^1' follow=off state=tiled focus=off
  bspc rule -a Firefox:Places desktop='^1' follow=off state=floating focus=off
  bspc rule -a Firefox:Firefox desktop='^1' follow=off state=floating focus=off
  bspc rule -a Thunderbird desktop='^3' follow=off state=tiled focus=off
  bspc rule -a Thunderbird:Calendar state=floating focus=on
  bspc rule -a Slack desktop='^5' state=tiled focus=off
  bspc rule -a TelegramDesktop desktop='^7' follow=off state=floating focus=off
  bspc rule -a yakuake sticky=on state=floating layer=above
  bspc rule -a Yad sticky=on state=floating layer=above
  bspc rule -a obsidian desktop='^4' follow=on focus=on state=tiled
  bspc rule -a dolphin desktop='^8' follow=on focus=on state=tiled
  bspc rule -a FortiClient desktop='^10' follow=off focus=on state=floating
fi

yakuake &
wmname LG3D
