#!/usr/bin/env zsh

function EGPU() {
  lspci | grep -q "GeForce GTX 1070"
  return $?
}

function externalMonitor() {
  xrandr | grep -q "HDMI-2 connected"
  return $?
}

function homeSetup() {
  ~/.screenlayout/home-dock.lt.sh
  bspc monitor DP-2 -d I II III IV V
  bspc monitor HDMI-0 -d VI VII VIII IX X
  sxhkd -c ~/.config/sxhkd/sxhkdrc-dock &
  ln -sf ~/.config/sxhkd/sxhkdrc-dock ~/.config/sxhkd/sxhkdrc
  ln -sf ~/.config/dunst/dunstrc-dock ~/.config/dunst/dunstrc
  ln -sf ~/Documents/Personal/private-configs/wallpapers/arch.png ~/.background
}

function officeSetup() {
  ~/.screenlayout/office-nodock.sh
  bspc monitor DP-2 -d I II III IV V
  bspc monitor HDMI-2 -d I II III IV V
  bspc monitor eDP-1 -d VI VII VIII IX X
  ln -sf ~/.config/sxhkd/sxhkdrc-nodock ~/.config/sxhkd/sxhkdrc
  ln -sf ~/.config/dunst/dunstrc-nodock ~/.config/dunst/dunstrc
  ln -sf ~/Documents/Personal/private-configs/wallpapers/arch.png ~/.background
}

function standaloneSetup() {
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
  ln -sf ~/.config/sxhkd/sxhkdrc-nodock ~/.config/sxhkd/sxhkdrc
  ln -sf ~/.config/dunst/dunstrc-nodock ~/.config/dunst/dunstrc
  ln -sf ~/Documents/Personal/private-configs/wallpapers/material-design-metal-colors-4k-n8.jpg ~/.background
}

function autostartApps() {
  xautolock -time 15 -locker ~/.config/i3lock/lock.sh -detectsleep &
  xsettingsd &
  wmname LG3D
  pkill dunst
  pkill picom
  pkill sxhkd
  dunst &
  picom -b --config ~/.config/picom/picom.conf
  feh --bg-fill ~/.background
  ~/.config/polybar/launch.sh &
  /usr/share/libpam-kwallet-common/pam_kwallet_init &
  yakuake &
  sxhkd &
}

if EGPU; then
  homeSetup
elif externalMonitor; then
  officeSetup
else
  standaloneSetup
fi

# BSPWM
bspc config focus_follows_pointer true
bspc config top_padding 33
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true
bspc config window_gap 5
bspc config split_ratio 0.52
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focused_border_color \#FEFEFE
bspc config normal_border_color \#111824
bspc config initial_polarity first_child
bspc config automatic_scheme longest_side

bspc config external_rules_command ~/.config/bspwm/external_rules.sh

if EGPU; then
  bspc desktop "^6" -l monocle
  bspc rule -a Firefox:Navigator desktop='^6' follow=off state=tiled focus=off
  bspc rule -a Firefox:Places desktop='^6' follow=off state=floating focus=off
  bspc rule -a Firefox:Firefox desktop='^6' follow=off state=floating focus=off
  bspc rule -a Thunderbird desktop='^8' follow=off state=tiled focus=off
  bspc rule -a Mailspring desktop='^8' follow=off state=tiled focus=off
  bspc rule -a Slack desktop='^10' state=tiled focus=off
  bspc rule -a TelegramDesktop desktop='^2' follow=off state=floating focus=off
  bspc rule -a obsidian desktop='^9' follow=on focus=on state=tiled
  bspc rule -a dolphin desktop='^3' follow=on focus=on state=tiled
  bspc rule -a FortiClient desktop='^9' follow=off focus=on state=floating
  bspc rule -a 'VirtualBox Manager':'VirtualBox Manager' desktop='^5' state=floating
else
  bspc desktop "^1" -l monocle
  bspc rule -a Firefox:Navigator desktop='^1' follow=off state=tiled focus=off
  bspc rule -a Firefox:Places desktop='^1' follow=off state=floating focus=off
  bspc rule -a Firefox:Firefox desktop='^1' follow=off state=floating focus=off
  bspc rule -a Thunderbird desktop='^3' follow=off state=tiled focus=off
  bspc rule -a Mailspring desktop='^3' follow=off state=tiled focus=off
  bspc rule -a Slack desktop='^5' focus=off
  bspc rule -a TelegramDesktop desktop='^7' follow=off state=floating focus=off
  bspc rule -a obsidian desktop='^4' follow=on focus=on state=tiled
  bspc rule -a dolphin desktop='^8' follow=on focus=on state=tiled
  bspc rule -a FortiClient desktop='^10' follow=off focus=on state=floating
  bspc rule -a 'VirtualBox Manager':'VirtualBox Manager' desktop='^10' state=floating
fi

bspc rule -a pavucontrol-qt state=tiled
bspc rule -a yakuake sticky=on state=floating layer=above
bspc rule -a Yad sticky=on state=floating layer=above
bspc rule -a Thunderbird:Calendar state=floating focus=on

autostartApps
